# CI with KVM virtualization on GH actions infra (slow, low storage, 6h timeout)
# - virualization provided by virtme
# - only x86_64, ARM virtualization not available

name: CI KVM

on:
  push:
    branches: [ "ci-kvm**" ]
  pull_request:
    branches: [ "ci-kvm**" ]

jobs:
  build:
    if: github.ref != 'refs/heads/ci-kvm'
    strategy:
      matrix:
        group: [ "-g quick", "-g dedupe" ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Host info
      run: |
        uname -a
        lscpu
        free -m
        df -h /
        lsblk
    - name: Update package cache
      run: sudo apt-get update -y
    - name: Install build and runtime dependencies
      run: sudo apt-get install -y bc gawk gcc git indent make sed flex bison libelf-dev udev virtme-ng
    - name: Setup KVM and virtme
      # Check version and that it can actually run on the host VM
      run: |
        sudo chmod 0644 /boot/vmlinuz-*
        sudo chmod 0666 /dev/kvm
        vng --version
        sudo vng --verbose -r -- uname -a
    # Pass the configs for initial setup and then again if localmod drops some something
    - name: Build kernel for virtme
      run: |
        vng --verbose --kconfig --config .github/workflows/kconfig.btrfs --config .github/workflows/kconfig.fstests
        #make localmodconfig
        cat .github/workflows/kconfig.btrfs .github/workflows/kconfig.fstests >> .config
        make olddefconfig
        vng --verbose --build
    - name: Test boot of built kernel
      run: sudo vng -- uname -a
    # Note: post-update could drop permissions from /dev/kvm
    - name: Install dependencies for fstests
      run: |
        sudo apt-get install -y acl attr autoconf automake bc dbench dump e2fsprogs fio gawk \
            gcc git indent libacl1-dev libaio-dev libcap-dev libgdbm-dev libtool \
            libtool-bin liburing-dev libuuid1 lvm2 make psmisc python3 quota sed \
            uuid-dev uuid-runtime xfsprogs linux-headers-$(uname -r) sqlite3 libgdbm-compat-dev \
            xfsdump xfslibs-dev btrfs-progs pkg-config duperemove
        sudo chmod 0666 /dev/kvm
    - name: Build fstests
      run: |
        git clone --depth 1 -b local https://github.com/kdave/xfstests $HOME/xfstests
        pushd $HOME/xfstests
        autoreconf -vfi
        ./configure
        make -j$(nproc)
        popd

    # Tests
    - name: Setup fstests environment
      run: |
        truncate -s 12g disk{1..9}
        pushd $HOME/xfstests
        sudo useradd --create-home fsgqa
        sudo useradd fsgqa2
        sudo useradd 123456-fsgqa
        sudo mkdir /mnt/test
        sudo mkdir /mnt/scratch
        echo export TEST_DEV=/dev/vda >> local.config
        echo export TEST_DIR=/mnt/test >> local.config
        echo export SCRATCH_DEV_POOL="'/dev/vdb /dev/vdc /dev/vdd /dev/vde /dev/vdf /dev/vdg /dev/vdh /dev/vdi'" >> local.config
        echo export LOGWRITES_DEV=/dev/vdi >> local.config
        echo export SCRATCH_MNT=/mnt/scratch >> local.config
        echo export FSTYP=btrfs >> local.config
        echo export MKFS_OPTIONS="'-K -f'" >> local.config
        echo export MOUNT_OPTIONS= >> local.config
        popd
    # With --rw we have full access to the host
    # FIXME: the mkfs.btrfs should run inside VM and take the MKFS_OPTIONS and TEST_DEV from config
    # VM setup:
    # - memory 4GiB
    # - cpus all from host (usually 4)
    - name: "Start fstests in VM: ${{ matrix.group }}"
      run: |
        sudo vng --memory 4096 --rw \
        --disk disk1 --disk disk2 --disk disk3 --disk disk4 --disk disk5 \
        --disk disk6 --disk disk7 --disk disk8 --disk disk9 \
        --user root --network user -- \
        "cd $HOME/xfstests; lscpu; free -m; cat /proc/partitions; cat local.config; \
         mkfs.btrfs /dev/vda ; \
         env --default-signal=PIPE ./check -R xunit -b -T ${{ matrix.group }}; \
         echo FSTESTS FINISHED"
    - name: Generate report
      uses: mikepenz/action-junit-report@v6
      if: success() || failure()
      with:
        annotate_only: true
        report_paths: "/home/runner/xfstests/results/result.xml"
    - name: Save results as artifacts
      uses: actions/upload-artifact@v6
      if: success() || failure()
      with:
        name: results
        path: "/home/runner/xfstests/results/"
    - name: Collect not run tests to summary
      if: success() || failure()
      run: /home/runner/xfstests/collect-notrun-to-summary.sh /home/runner/xfstests >> $GITHUB_STEP_SUMMARY
